# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Track.create(title:"bass1", reference:"../../Back-End/Audio/bass/bass1.mp3")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
# Track.create(title:"", reference:"")
