# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Track.create(title:"bass1", reference:"../../SoundBoard/Back-End/Audio/bass/bass1.mp3")
Track.create(title:"bass2", reference:"../../SoundBoard/Back-End/Audio/bass/bass2.mp3")
Track.create(title:"bass3", reference:"../../SoundBoard/Back-End/Audio/bass/bass3.mp3")
Track.create(title:"bass4", reference:"../../SoundBoard/Back-End/Audio/bass/bass4.mp3")
Track.create(title:"bass5", reference:"../../SoundBoard/Back-End/Audio/bass/bass5.mp3")
Track.create(title:"drums1", reference:"../../SoundBoard/Back-End/Audio/drums/drums1.mp3")
Track.create(title:"drums2", reference:"../../SoundBoard/Back-End/Audio/drums/drums2.mp3")
Track.create(title:"drums3", reference:"../../SoundBoard/Back-End/Audio/drums/drums3.mp3")
Track.create(title:"drums4", reference:"../../SoundBoard/Back-End/Audio/drums/drums4.mp3")
Track.create(title:"drums5", reference:"../../SoundBoard/Back-End/Audio/drums/drums5.mp3")
Track.create(title:"keys1", reference:"../../SoundBoard/Back-End/Audio/keys/keys1.mp3")
Track.create(title:"keys2", reference:"../../SoundBoard/Back-End/Audio/keys/keys2.mp3")
Track.create(title:"keys3", reference:"../../SoundBoard/Back-End/Audio/keys/keys3.mp3")
Track.create(title:"keys4", reference:"../../SoundBoard/Back-End/Audio/keys/keys4.mp3")
Track.create(title:"keys5", reference:"../../SoundBoard/Back-End/Audio/keys/keys5.mp3")
Track.create(title:"lead1", reference:"../../SoundBoard/Back-End/Audio/lead/lead1.mp3")
Track.create(title:"lead2", reference:"../../SoundBoard/Back-End/Audio/lead/lead2.mp3")
Track.create(title:"lead3", reference:"../../SoundBoard/Back-End/Audio/lead/lead3.mp3")
Track.create(title:"lead4", reference:"../../SoundBoard/Back-End/Audio/lead/lead4.mp3")
Track.create(title:"lead5", reference:"../../SoundBoard/Back-End/Audio/lead/lead5.mp3")
Track.create(title:"vocal1", reference:"../../SoundBoard/Back-End/Audio/vocal/vocal1.mp3")
Track.create(title:"vocal2", reference:"../../SoundBoard/Back-End/Audio/vocal/vocal2.mp3")
Track.create(title:"vocal3", reference:"../../SoundBoard/Back-End/Audio/vocal/vocal3.mp3")
Track.create(title:"vocal4", reference:"../../SoundBoard/Back-End/Audio/vocal/vocal4.mp3")
Track.create(title:"vocal5", reference:"../../SoundBoard/Back-End/Audio/vocal/vocal5.mp3")